### PR TITLE
Add links to Teller and Assemble website and remove "Coming Soon"

### PR DESCRIPTION
**Pull request by cryptounknown**
An update to Teller and Assemble to link to their respective websites.

### CODE REVIEW

**Comment by hesterbruikman** [comment]
Congratulations on your first PR!

Want to call in some advice. Both Teller and Assemble are very much in an experimental phase. On mainnet, but with a disclaimer because the contracts haven't been audited. 

Wdyt? @j-zerah @ceripower @iurimatias

**Comment by ceripower** [comment]
I think fine for assemble to be linked, we have a warning at the top that it's an experiment 👍

Also awesome to see you here @cryptounknown !

**Comment by cryptounknown** [comment]
I added an "Experimental" tag that pops up exactly how "Coming Soon" did. Just as an extra warning.

Also, thanks for the welcome @ceripower and @hesterbruikman! I had no idea that I was able to contribute like this. It's fun!

**Review by jakubgs — APPROVED** [review]
Looks good, but in the future please make PRs against the `develop` branch. The `master` branch deploys directly to prod, and `develop` allows us to test changes at https://dev.statusnetwork.com/.

**Comment by jakubgs** [comment]
Thanks for the contribution!

**Pull request merged**
